redhat-developer/devspaces-images

codeready-workspaces-plugin-openshift/Dockerfile
codeready-workspaces-plugin-openshift/get-sources-jenkins.sh

Use odo 2.0.0 which is required for vscode-openshift-tooling 0.2.0
Part of CRW-1259

Update the OpenShift connector sidecar

---

codeready-workspaces-plugin-java11/get-sources-jenkins.sh
codeready-workspaces-plugin-java8/get-sources-jenkins.sh

As we have dedicated openj9 based java8/11 repos , no need to pass
"--target crw-${JOB_BRANCH}-openj9-rhel-8-containers-candidate" to rhpkg for this repo.
@nickboldt / @kcrane   - Can you please help review this PR ?

Removing target flag to be passed to "rhpkg" command

---

codeready-workspaces-plugin-java11-openj9/container.yaml
codeready-workspaces-plugin-java11-openj9/content_sets.yml
codeready-workspaces-plugin-java11-openj9/get-sources-jenkins.sh
codeready-workspaces-plugin-java8-openj9/container.yaml
codeready-workspaces-plugin-java8-openj9/content_sets.yml
codeready-workspaces-plugin-java8-openj9/get-sources-jenkins.sh

SPMM-2745 this could be the change that Chris was describing in order to switch to the new j9 content sets and drop the need for package-level deps
if the first commit works, we can omit the crw-JOB_BRANCH-openj9-rhel-8-containers-candidate target when building these the j9 images
Change-Id: Icb29d87a355fdb5e0dcca35666cdecd1c58a47d2

SPMM-2745 this could be the change that Chris was describing in order to switch to the new j9 content sets and drop the need for package-level deps

---

codeready-workspaces-plugin-kubernetes/Dockerfile
codeready-workspaces-plugin-kubernetes/get-sources-jenkins.sh

it is the default used by VS Code Extension Tooling for Apache Camel K
0.0.18
nota: this is a blind commit. I haven't a local environment to test it.
is this file needs to be updated too?
How?
https://github.com/redhat-developer/codeready-workspaces-images/blob/crw-2.5-rhel-8/codeready-workspaces-plugin-kubernetes/sources

CRW-1298 - Upgrade default Kamel from 1.1.1 to 1.2.0

---

codeready-workspaces-plugin-java8-openj9/Dockerfile
codeready-workspaces-plugin-java8/Dockerfile

fix for unpacking python lang server and pylint into /usr/bin and /usr/lib* instead of /opt/app-root/bin and /opt/app-root/lib*
Depends on https://github.com/redhat-developer/codeready-workspaces-deprecated/pull/65
Change-Id: I96d4d2df1a0e75f1f24af943060f1d451df8dba5

fix for unpacking python lang server and pylint into /usr/bin and /usr/lib* instead of /opt/app-root/bin and /opt/app-root/lib*

---

codeready-workspaces-plugin-java11-openj9/Dockerfile
codeready-workspaces-plugin-java11-openj9/get-sources-jenkins.sh
codeready-workspaces-plugin-java11/Dockerfile
codeready-workspaces-plugin-java11/get-sources-jenkins.sh
codeready-workspaces-plugin-java8-openj9/Dockerfile
codeready-workspaces-plugin-java8-openj9/get-sources-jenkins.sh
codeready-workspaces-plugin-java8/Dockerfile
codeready-workspaces-plugin-java8/get-sources-jenkins.sh

Providing lombok.jar to be activated from a devfile:
```yaml
- id: redhat/java11/latest
preferences:
java.jdt.ls.vmargs: '-javaagent:/lombok.jar'
```
Reference issue: https://issues.redhat.com/browse/CRW-1420
Tested java11 plugin with this devfile in devsandbox (would only work in devsandbox as I have hardcoded the extension urls to devsandbox plugin registry):
```yaml
apiVersion: 1.0.0
metadata:
generateName: java-lombok-
projects:
- name: lombok-project-example
source:
location: 'https://github.com/chuucks/LOMBOK-PROJECT-EXAMPLE'
type: git
branch: master
components:
- preferences:
java.jdt.ls.vmargs: '-javaagent:/lombok.jar'
java.server.launchMode: Standard
type: chePlugin
reference: 'https://gist.github.com/sunix/6a5b8da1f15390436b5faca775391278/raw/c04ca692d6d1dc2550c79e3483227bf0249d0 …
```

CRW-1420 Providing lombok.jar for Java plugin to be activated from a devfile

---

codeready-workspaces-stacks-php/Dockerfile

Part of https://issues.redhat.com/browse/CRW-1335
2 other PR are coming to complete https://issues.redhat.com/browse/CRW-1335:
- https://github.com/redhat-developer/codeready-workspaces-deprecated/pull/73
- update php-di sample project to use the latest https://github.com/crw-samples/demo/pull/2

CRW-1335 upgrade php stack to php 7.4

---

codeready-workspaces-dashboard/build/scripts/sync.sh

This turns:
```Dockerfile
RUN yarn install
```
inside of rhel.Dockerfile to
```Dockerfile
COPY asset-yarn-cache.tgz /tmp/
RUN tar xzf /tmp/asset-yarn-cache.tgz -C .yarn/cache && rm -f /tmp/asset-yarn-cache.tgz
RUN yarn install
```
so that all the yarn cache resources are in the image before `yarn install` is run

Copy in the yarn cache resources before yarn install in the dashboard

---

codeready-workspaces-pluginregistry/bootstrap.Dockerfile
codeready-workspaces-pluginregistry/build/scripts/sync.sh
codeready-workspaces-pluginregistry/get-sources-jenkins.sh

* Create and commit bootstrap.Dockerfile -- don't generate it with sed
* Inside bootstrap.Dockerfile we generate the plugin registry meta.yamls/artifacts without pushing an image
* Tar those up into a tar archive called resources.tgz
* Business as usual after that
Part of CRW-1648

Adapt to the new plugin registry

---

codeready-workspaces-devworkspace/build/scripts/sync.sh

Currently it looks like `-mod=vendor` gets added on the same line as `go build` like: `go build \ -mod=vendor -x \`. In order to get everything to build correctly `-mod=vendor` has to be on a newline. The real fix is probably for the devworkspace-che-operator to use go 1.14 though

Add in newline before -mod=vendor when syncing

---

codeready-workspaces-devworkspace/build/scripts/sync.sh

With the adoption of go 1.14 in devworkspace-che-operator we no longer have to specify `-mod=vendor`. It should automatically pick it up as long as the vendor folder is there.
Related PR: https://github.com/che-incubator/devworkspace-che-operator/pull/44

Remove -mod=vendor from sed command in devworkspace-che-operator

---

codeready-workspaces-dashboard/build/scripts/patch-remove-pnp-plugin.diff
codeready-workspaces-dashboard/build/scripts/sync.sh
codeready-workspaces-dashboard/get-sources-jenkins.sh

Since IBM Z does not support yarn 2 yet, we're stuck with yarn 1.
Not to move upstream back, we're switching to yarn 1 during source sync.
This PR is WIP due the following TODOs:
Thanks @akurinnoy for the idea and help on preparing all the needed commands.

Switch dashboard to yarn 1

---

codeready-workspaces-dashboard/build/scripts/sync.sh

This PR makes it so that all dashboard dependencies are removed on sync. It also removes `COPY .yarnrc.yml /dashboard/` from the Dockerfile since that's not relevant when building with yarn v1

fix: Remove dashboard dependencies

---

codeready-workspaces-dashboard/build/scripts/sync.sh

This PR patches the rhel.Dockerfile directly so that both the rhel.Dockerfile and the root Dockerfile won't have `COPY .yarnrc.yml /dashboard/`

Patch both the dashboard rhel.Dockerfile and the root Dockerfile

---

codeready-workspaces-dashboard/build/scripts/sync.sh
codeready-workspaces-dashboard/yarn.lock

This PR changes the way we switch to yarn v1 because the current way leads to compile errors(see details below), we're not sure about the real cause.
Anyway, it's a simpler way to switch to yarn 1, since we have yarn1 binary in source code, in the same way we do with yarn v2.
In fact, what is changed, instead of generating yarn.lock v1 based on yarn v2 work, we generate yarn.lock v1, based on the previous version we have in downstream.
yarn.lock file I've added in PR is the last we had in upstream before we switched to yarn v2 https://github.com/eclipse-che/che-dashboard/blob/e4dad7100e32d3a865582e73818647c0df90d0bd/yarn.lock
So far I've checked that sync.sh works fine and after that I'm able to build bootstrap container, which failed previously with the errors below.
Many thanks …

Change the way we switch to yarn v1

---

codeready-workspaces-dashboard/build/scripts/sync.sh

fix: No longer pin the devworkspace-client to a specific version

---

codeready-workspaces-devworkspace-controller/build/scripts/sync.sh

With this PR:
```
RUN go env GOPROXY && \
go mod download
```
will get transformed into:
```
#RUN go env GOPROXY && \
#go mod download
```
after syncing

fix: improved handling for devworkspace controller dockerfile

---

codeready-workspaces-dashboard/build/dockerfiles/rhel.Dockerfile
codeready-workspaces-dashboard/build/scripts/sync.sh

Fixed typo `--ignore-engine` => `--ignore-engines`

Fix typo in the dashboard synchronization script

---

codeready-workspaces-dashboard/packages/dashboard-frontend/assets/branding/product.json.template

Adapt CRW dashboard to a newer product.json.template from https://github.com/eclipse-che/che-dashboard/pull/294
+ update request feature link
It should fix https://issues.redhat.com/browse/CRW-1879

Adapt CRW dashboard to a newer product.json.template & update request feature link

---

codeready-workspaces-idea/build/scripts/sync.sh
codeready-workspaces-idea/get-sources.sh

According to rules for naming the assets which are included in Brew build, update the `sync.sh` and `get-sources.sh`.
Updated assets name available in upstream branch: https://github.com/che-incubator/jetbrains-editor-images/tree/20210728 which is based on latest released tag: https://github.com/che-incubator/jetbrains-editor-images/releases/tag/20210728.f3dcdf6

Change asset's names according to brew conventions

---

codeready-workspaces-idea/get-sources.sh

Projector sources build using Gradle Wrapper by calling:
```
./gradlew :projector-server:distZip
```
under the hood of `./projector.sh` shell script. As a requirement, JDK 11 should be installed and `JAVA_HOME` env variable should be configured.

Install JDK as requirement for building Projector sources

---

codeready-workspaces-dashboard/packages/dashboard-frontend/assets/branding/product.json
codeready-workspaces-dashboard/packages/dashboard-frontend/assets/branding/product.json.template

This PR removes the trailing comma from links in product.json. This seems to fix https://issues.redhat.com/browse/CRW-2176

fix: Remove trailing comma from links in product.json

---

codeready-workspaces-operator-bundle/build/scripts/sync-che-olm-to-crw-olm.sh
codeready-workspaces-operator-bundle/build/scripts/sync-che-operator-to-crw-operator.sh
codeready-workspaces-operator-bundle/manifests/codeready-workspaces.crd.yaml
codeready-workspaces-operator-bundle/manifests/codeready-workspaces.csv.yaml
codeready-workspaces-operator-metadata/build/scripts/sync-che-olm-to-crw-olm.sh

It is not possible to have 2 channels with the same CSV name. I sync like in upstream adding to new channel the suffix `-all-namespaces` to CSV
Also this PR remove from Operator HUB UI the option to enable devworkspace and will be enabled by default in `tech-preview-latest-all-namespaces`
Upstream issue: https://github.com/eclipse/che/issues/20392
Signed-off-by: Flavius Lacatusu <flacatus@redhat.com>

fix: Enable devWorkspace by default in `tech-preview-*` channel and deprecate from `latest` channel

---

codeready-workspaces-plugin-java8/Dockerfile
codeready-workspaces-plugin-java8/entrypoint.sh

Enabling prebuilt venv with all the dependencies to start python jupyter server
to be tested with https://github.com/redhat-developer/codeready-workspaces-deprecated/pull/76 and this devfile:
```yaml
apiVersion: 1.0.0
metadata:
generateName: python-dev-jupyter-
projects:
- name: jupyter-hello-world1
source:
location: 'https://github.com/chasbecker/TextAnalysis.git'
startPoint: master
type: git
components:
- id: ms-python/python/latest
preferences:
python.globalModuleInstallation: true
type: chePlugin
registryUrl: 'https://sunix-crw-plugin-registry-dev-103m5.surge.sh/v3'
- mountSources: true
memoryLimit: 512Mi
type: dockerimage
volumes:
- name: venv
containerPath: /home/jboss/.venv
alias: python
image: 'quay.io/sunix/che-plugin-sidecar:crw-java8'
- id: eclipse/che-theia/latest
type: …
```

feat(python-jupyter): enabling prebuilt venv with all the dependencies to start python jupyter server

---

codeready-workspaces-operator-metadata/build/scripts/sync-che-olm-to-crw-olm.sh
codeready-workspaces-operator-metadata/build/scripts/sync-che-operator-to-crw-operator.sh

From https://github.com/eclipse-che/che-operator/pull/1065 we introduce a new environment which disable and enabled devworkspace engine
Signed-off-by: Flavius Lacatusu <flacatus@redhat.com>

Make ALLOW_DEVWORKSPACE_ENGINE env false in latest channel

---

codeready-workspaces-plugin-java8-openj9/Dockerfile
codeready-workspaces-plugin-java8-openj9/entrypoint.sh

Signed-off-by: Sun Seng David TAN <sutan@redhat.com>
Applying https://github.com/redhat-developer/codeready-workspaces-images/pull/51/files for Z&P/openj9 sidecar

feat(python-jupyter): enabling prebuilt venv with all the dependencies to start python jupyter server - Z&P - openj9 sidecar

---

codeready-workspaces-dashboard/build/scripts/sync.sh

Change the way we install yarn in .yarn/releases
We can't use set-policies anymore since it relies
on an ability to set GitHub token as query param
while header now is required.
See for more details https://github.com/yarnpkg/yarn/issues/7847
Will be tested by build pipeline after merging.

Change the way we install yarn in .yarn/releases

---

codeready-workspaces-dashboard/build/scripts/sync.sh

We can't use set-policies anymore since it relies
on an ability to set GitHub token as query param
while header now is required.
See for more details https://github.com/yarnpkg/yarn/issues/7847
it's actually backport of what was done against crw-2.12 branch:
https://github.com/redhat-developer/codeready-workspaces-images/pull/106
https://github.com/redhat-developer/codeready-workspaces-images/pull/107

fix: change the way we install yarn in .yarn/releases

---

codeready-workspaces-operator-metadata/build/scripts/sync-che-olm-to-crw-olm.sh

CSV date will be updated, only if there were actual changes after the sync. This will prevent spam of syncing, where only date is being updated
Signed-off-by: Mykhailo Kuznietsov <mkuznets@redhat.com>

fix: prevent op-metadata sync from needlessly updating createdAt'

---

codeready-workspaces-operator-bundle/build/scripts/sync-che-olm-to-crw-olm.sh
codeready-workspaces-operator-bundle/build/scripts/sync-che-operator-to-crw-operator.sh

fix: CRW-2303 - re-enable RELATED_IMAGE_gateway_authentication_sidecar and RELATED_IMAGE_gateway_authorization_sidecar; use https://catalog.redhat.com/software/containers/openshift4/ose-kube-rbac-proxy/5cdb2634dd19c778293b4d98?container-tabs=gti and https://catalog.redhat.com/software/containers/openshift4/ose-oauth-proxy/5cdb2133bed8bd5717d5ae64?container-tabs=gti
N/A
https://issues.redhat.com/browse/CRW-2303?
N/A

fix: CRW-2303 - re-enable RELATED_IMAGE_gateway_authentication_sidecar and RELATED_IMAGE_gateway_authorization_sidecar

---

codeready-workspaces-operator-metadata/build/scripts/sync-che-olm-to-crw-olm.sh

https://issues.redhat.com/browse/CRW-2416
This pr should fix custom resource https://github.com/redhat-developer/codeready-workspaces-images/blob/5beb480ab9cff5f54bb6188d8ebfc9e472006155/codeready-workspaces-operator-metadata-generated/manifests/codeready-workspaces.csv.yaml#L23 . We have to use `CheCluster` CR instead of `CheBackupServerConfiguration`. 
Alternative(not covered in the pr): or we could use all CRs from che-operator CR.
Signed-off-by: Oleksandr Andriienko <oandriie@redhat.com>

fix: Fix failing CRW 2.13 installation.

---

codeready-workspaces-configbump/get-sources.sh
codeready-workspaces-plugin-kubernetes/get-sources.sh

Fix: found 2 get-sources files that still used fetch-assets when they should be using pull-assets

Merge fix for get-sources script

---

codeready-workspaces-udi-openj9/Dockerfile
codeready-workspaces-udi-openj9/get-sources.sh
codeready-workspaces-udi/Dockerfile
codeready-workspaces-udi/get-sources.sh

For CRW-2689
https://issues.redhat.com/browse/CRW-2689

Fix: update odo version to v2.5.0 and use new mirror url

---

codeready-workspaces-devfileregistry/bootstrap.Dockerfile

Signed-off-by: Igor Vinokur <ivinokur@redhat.com>
In order to fix `jq: error: Could not open file versions.json: No such file or directory` error from the `generate_devworkspace_templates.sh` script, add the `versions.json` file to the `bootstrap.Dockerfile`

fix: Add versions.json file to the bootstrap.Dockerfile build

---

codeready-workspaces-devfileregistry/tests/basic-test.yaml

Signed-off-by: Igor Vinokur <ivinokur@redhat.com>
Add test which lists `devworkspace-che-theia-latest.yaml` in the `devfiles` directory, or returns `exit code 1`, if no templates found.

chore: Add test to check devfile templates generation

---

codeready-workspaces-udi/Dockerfile

Signed-off-by: svor <vsvydenk@redhat.com>
Adds user and configure it in UDI. It should fix a problem with folder creation in `/home/user` like `/home/user/.m2` during the maven build command.

chore: add user into UDI

---

codeready-workspaces-udi-openj9/Dockerfile
codeready-workspaces-udi/Dockerfile

fix: bin.tgz got renamed to asset-odo.tgz

Fixes for CRW-2464

---

codeready-workspaces-udi/Dockerfile
codeready-workspaces-udi/etc/entrypoint.sh

Signed-off-by: Vitaliy Gulyy <vgulyy@redhat.com>
- Instead of copying `/home/user/.venv-tmp` to `/home/user/.venv` on container startup, it's better to prepare `/home/user/.venv` when building the UDI image. It reduces the workspace startup time by around one minute (the time required to moving resources https://github.com/redhat-developer/codeready-workspaces-images/blob/crw-2-rhel-8/codeready-workspaces-udi/etc/entrypoint.sh#L43 ).
- It improves the terminal prompt as well.

chore: prepare /home/user/.venv directory when building UDI container

---

codeready-workspaces-dashboard/build/scripts/sync.sh

Hard code a warning message in the dashboard about the upcoming DevWorkspace engine migration. Message copy is still WIP and link is a TODO.
This is a really ugly solution, but my other attempts to do this ran into dead ends:
* The dashboard reads the warning message directly from the CheCluster custom resource, via the Kubernetes API, meaning the operator deployment has no interaction in the flow (i.e. the patch can't go in the codeready-workspaces-operator conversion)
* I tried setting a default value in the custom resource to set the warning, but
* existing CheClusters will not get the default value applied (I think...)
* even if they did, once set it would need to be manually un-set to undo the patch
Instead, this replacement just updates
```typescript
if …
```

Temporarily hard-code dashboard warning message about move to DW engine

---

codeready-workspaces-dashboard/build/scripts/sync.sh

Rework https://github.com/redhat-developer/devspaces-images/pull/204 so that deprecation warning can be overridden.
Showing default warning message:
Default warning message when the frontend can't connect to the backend:
Overriding warning message:
Overriding warning message with empty string (banner still shows up by is smaller and contains no text):
Diff from script applied to on dashboard 7.42.x: https://github.com/amisevsk/che-dashboard/commit/08d88a4b6386aeb6f5faa253533f4b31fabde958

Hard-code warning message about move to DW but make it configurable

---

devspaces-udi/etc/entrypoint.sh

It's not possible to execute commands with **sudo** in entrypoint.sh. Can we proceed without removing unused _/etc/alternatives/java_ and _/etc/alternatives/javac_?
Fix for https://issues.redhat.com/browse/CRW-2862

fix:cleanup entrypoint.sh for UDI

---

devspaces-devfileregistry/build/dockerfiles/entrypoint.sh
devspaces-operator-bundle/build/scripts/insert-related-images-to-csv.sh

fix: CRW-2887 - when running update_container_image_references(), process meta.yaml and devworkspace-che-theia-latest.yaml too
Change-Id: I5afc03584be8b6e1a606f60a69e07737c8381ec5
N/A
N/A

fix: CRW-2887 - when running update_container_image_references(), process meta.yaml and devworkspace-che-theia-latest.yaml too

---

devspaces-operator-bundle/build/scripts/insert-related-images-to-csv.sh

…devfile registry
Adds images used by editor component into csv as a related image for the devfile registry

fix: CRW-2887 - add editor's images into csv as devfile related image

---

devspaces-idea/build/scripts/sync.sh

Improve sed instruction to avoid having `ubi8/ubi:8.5-214 as ubi-builder`. Improved command provides correct image for Brew build: `FROM ubi:8.5-214 as ubi-builder`

Improve sed by adding check for ubi8 image

---

devspaces-idea/build/scripts/sync.sh

Fix sed instruction to change name for ubi8 image from:
```
FROM registry.access.redhat.com/ubi8/ubi:8.5-214 as ubi-builder
```
to
```
FROM ubi8:8.5-214 as ubi-builder
```

Fix sed command for ubi8 image name

---

devspaces-udi/Dockerfile
devspaces-udi/get-sources.sh

Port changes from upstream https://github.com/devfile/developer-images/commit/9436df267516e12b96fb59b4b12814c70ecdf558 to downstream UDI.
Build `e2fsprogs` for x86 only as far as this library is required for IntelliJ IDEA Community Edition and it runs only on x86 platform.
Part of https://issues.redhat.com/browse/CRW-2977

Add e2fsprogs bundle for x86 platform

---

devspaces-idea/get-sources.sh

Use IntelliJ IDEA Community Edition 2022.1 instead 2020.3.4

Update IC tarball to 2022.1 version

---

devspaces-operator-bundle/build/scripts/sync-che-olm.sh
devspaces-operator-bundle/build/scripts/sync.sh

This PR modifies `devspaces-operator-bundle` build scripts to re-enable the 'replaces' directive in csv:
- sync-che-olm.sh
- sync.sh
It's related to https://issues.redhat.com/browse/CRW-2725
Signed-off-by: Dmytro Nochevnov <dnochevn@redhat.com>

Re-enable the 'replaces' directive in 'devspaces-operator-bundle' build

---

devspaces-operator-bundle/build/scripts/sync-che-operator.sh
devspaces-operator/build/scripts/sync-che-operator.sh

Wee need deploy folder. It contains resources for chectl/dsc.
To fix build https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/CRW_CI/job/dsc_3.x/

Keep deploy folder

---

devspaces-idea/get-sources.sh

Adapt `get-sources.sh` script to accept new asset which is needed for machine-exec support.
Part of https://github.com/redhat-developer/devspaces/pull/749

Update idea-based editor

---

devspaces-pluginregistry/bootstrap.Dockerfile

Don't copy non existing files
Related issue: https://issues.redhat.com/browse/CRW-3110

chore: don't copy yarn.lock

---

devspaces-code/build/scripts/collect-assets.sh

Use github token at building libc docker image.
The corresponding PR in the upstream is: https://github.com/che-incubator/che-code/pull/66
The changes should fix errors like:
```
23:39:26 23:39:26  GET https://api.github.com/repos/microsoft/ripgrep-prebuilt/releases/tags/v13.0.0-4
23:39:26 23:39:26  Deleting invalid download cache
23:39:26 23:39:26  Downloading ripgrep failed: Error: Request failed: 403
23:39:26 23:39:26      at ClientRequest.<anonymous> (/checode-compilation/node_modules/@vscode/ripgrep/lib/download.js:143:24)
23:39:26 23:39:26      at Object.onceWrapper (node:events:640:26)
23:39:26 23:39:26      at ClientRequest.emit (node:events:520:28)
23:39:26 23:39:26      at HTTPParser.parserOnIncomingClient (node:_http_client:618:27)
23:39:26 23:39:26      at …
```

fix: Use github token at building libc docker image

---

devspaces-code/build/dockerfiles/libc-content-provider.Dockerfile

Add debug log for Code dockerfile
I got an error:
`20:53:02 20:53:02  [17:53:02] 'vscode-reh-web-linux-x64-min' errored after 5.18 min
20:53:02 20:53:02  [17:53:02] Error: EMFILE: too many open files, open '/checode-compilation/node_modules/jest-worker/build/workers/threadChild.js'`
So, I would like to add that log, maybe it could clarify the cause of the problem...

Add debug log for Code

---

devspaces-code/Dockerfile

Fix build of docker image on brew
We get an error like:
```
16:26:18 16:26:18  2022-07-14 13:26:11,037 - atomic_reactor.plugins.imagebuilder - INFO - API error (500): Error processing tar file(exit status 1): remove /etc/hosts: device or resource busy
16:26:18 16:26:18  2022-07-14 13:26:11,040 - atomic_reactor.plugin - ERROR - Build step plugin imagebuilder failed: image build failed (rc=1): API error (500): Error processing tar file(exit status 1): remove /etc/hosts: device or resource busy
``` 
at building docker image on brew.
There is no such problem when we build the same image locally, but it's really a problem for brew...
The change should fix the problem. 

fix: Fix build of docker image on brew

---

devspaces-udi/Dockerfile

Print the default Java version during the build of UDI
The output is:
```
#7 0.294 ========
#7 0.294 Default Java Version:  openjdk version "11.0.15" 2022-04-19 LTS
#7 0.324 OpenJDK Runtime Environment 18.9 (build 11.0.15+10-LTS)
#7 0.324 OpenJDK 64-Bit Server VM 18.9 (build 11.0.15+10-LTS, mixed mode, sharing)
#7 0.328 ========
#7 0.328 Java 1.8:  openjdk version "1.8.0_332"
#7 0.384 OpenJDK Runtime Environment (build 1.8.0_332-b09)
#7 0.384 OpenJDK 64-Bit Server VM (build 25.332-b09, mixed mode)
#7 0.387 ========
#7 0.387 Java 11:  openjdk version "11.0.15" 2022-04-19 LTS
#7 0.415 OpenJDK Runtime Environment 18.9 (build 11.0.15+10-LTS)
#7 0.415 OpenJDK 64-Bit Server VM 18.9 (build 11.0.15+10-LTS, mixed mode, sharing)
#7 0.418 …
```

chore: print default java version

---

devspaces-code/container.yaml

Enable 390x platform for building Code images
https://issues.redhat.com/browse/CRW-3171
[These changes](https://github.com/che-incubator/che-code/commit/4dcc762243664ecc7a40a33b981d4d98dc237528) should fix build for Code on `s390x` platform

Enable 390x platform for building Code images

---

devspaces-traefik/build/scripts/sync.sh

https://issues.redhat.com/browse/CRW-3136
@nickboldt new plan, instead of updating 700 files I'm going to update the sync script to 2.8.1 then build devspaces-traefik in jenkins and let _that_ do the heavy lifting.

Update Traefik to 2.8.1

---

devspaces-udi/Dockerfile

Signed-off-by: Mykhailo Kuznietsov <mkuznets@redhat.com>
this GOPATH definition is not needed, since we rely on default GOPATH pointing to /home/user/go

fix: Remove unneeded GOPATH for UDI image

---

devspaces-udi/Dockerfile

chore: CRW-3159 remove dotnet 3.1 (EOL Dec 13, 2022 - see https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core) (#382)
Change-Id: Ic739716dbe343ab57485da08c46d02750ccd19f9
N/A
N/A

chore: CRW-3159 remove dotnet 3.1 (EOL Dec 13, 2022 - see https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core)

---

devspaces-udi/Dockerfile
devspaces-udi/fetch-artifacts-pnc.yaml

Since VSCode redhat.java extension doesn't require the path to lombok.jar we can avoid adding lombok.jar into UDI 
Related issue: https://issues.redhat.com/browse/CRW-3602

chore: don't add lombok.jar into UDI

---

devspaces-code/branding/product.json

`Restart Workspace from Local Devfile` action was added in the upstream, see https://github.com/che-incubator/che-code/pull/185.
The current PR provides `Dev Spaces` label for the `Restart Workspace from Local Devfile` action.

Provide Dev Spaces label for the 'Restart Workspace from Local Devfile' action

---

devspaces-code/branding/product.json

`Open OpenShift Console` action is going to be added to the upstream, see https://github.com/che-incubator/che-code/pull/191.
The current PR provides `Dev Spaces` label for the `Open OpenShift Console` action.

Provide Dev Spaces label for the 'Open OpenShift Console' action

---

devspaces-code/build/dockerfiles/content_sets_pulp.repo
devspaces-code/build/dockerfiles/libc-content-provider.Dockerfile
devspaces-code/build/scripts/sync.sh

code_3.x build fails on x86_64, s390x and ppc64le due to the following 2 reasons:
1. Failed to find module '**native-keymap**'. There was a command in the script used for syncing with upstream project which deletes the 'native-keymap' module. The command has been removed from the sync script.
2. The build requires 2 packages (**libsecret** & **libxkbfile**) to be installed into the image. The RPMs are not available at the default ubi8 yum repositories. Therefore, pulp content sets is enabled to install libsecret & libxkbfile as rpm.

Fix: CRW-4120 Removing command to delete 'native-keymap' module in sync script and enabling pulp content sets to resolve libsecret & libxkbfile as rpm

---

devspaces-devfileregistry/build/scripts/sync.sh
devspaces-devfileregistry/tests/basic-test.yaml
devspaces-pluginregistry/Dockerfile
devspaces-pluginregistry/build/scripts/sync.sh

Since che-theia-plugins.yaml an che-plugins.yaml don't exist anymore, update a sync script in the plugin registry

fix: update sync.sh to remove references to theia plugins

---

devspaces-code/branding/product.json

Backports https://github.com/redhat-developer/devspaces-images/pull/432 to 3.6

Backport of 432 PR to 3.6

---

devspaces-code/branding/product.json

Fixes: https://issues.redhat.com/browse/CRW-4114
The upstream changes: https://github.com/che-incubator/che-code/pull/216
Tested in upstream:

feat: Provide branding for the Welcome page subtitle

---

devspaces-code/build/dockerfiles/content_sets_pulp.repo
devspaces-code/container.yaml

Change-Id:...
switch to https; re-enable Z & P
Change-Id: I07b1d8afe4b1f345ba36f30966a94370b60bd7fe
N/A
N/A

switch to https; re-enable Z & P

---

devspaces-code/branding/product.json
devspaces-code/code/product.json

Depends on:
- https://github.com/che-incubator/che-code/pull/219
- https://github.com/che-incubator/che-code/pull/223
Provides branding for the Welcome page
- value of the `welcomePageTitle` field is used as the `Welcome` page title
- value of the `welcomePageSubtitle` field is used as the `Welcome` page subtitle
- `nameLong` is still used for the `About` dialog and browser tab title

feat: Provide branding for the Welcome page

---

devspaces-dashboard/build/scripts/sync.sh

Now we want to show che-idea editor in the User Dashboard, issue about that:
https://issues.redhat.com/browse/CRW-4139
Also we don't need to exclude che-theia editor since it was removed from the plugin registry and it doesn't exist at all

chore: don't exclude IDEA in the dashboard editor's view

---

devspaces-operator-bundle/build/scripts/insert-related-images-to-csv.sh

Don't add images that match pattern from excludedImagePatterns into the CSV file as a RELATED IMAGE variable
Related issue: https://issues.redhat.com/browse/CRW-4359

feat: don't add ansible-creator-ee image into csv RELATED_IMAGES

---

devspaces-udi/Dockerfile

This is a fix for https://issues.redhat.com/browse/CRW-4517
I have tested using this [Dockerfile](https://gist.github.com/l0rd/c48f38c5220c64af5699a214fb7e64c3) that I have pushed it here: `quay.io/mloriedo/universal-developer-image:chgrp`
```Dockerfile
FROM registry.redhat.io/devspaces/udi-rhel8
USER root
RUN mkdir -p /home/user && chgrp -R 0 /home && chmod -R g=u /home
```
I tested that I could run `npm install nodeshift` successfully:
```
$ npm install nodeshift
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated …
```

Arbitrary users in UDI should have $HOME write access

---

devspaces-operator-bundle/build/scripts/insert-related-images-to-csv.sh

With these changes **quay.io/devspaces/ansible-creator-ee** image won't be included in the list of RELATED IMAGES in devspaces.csv file. It should fix the build on brew.
Related issue: https://issues.redhat.com/browse/CRW-4541

chore: don't include ansible-creator-ee into related images

---

devspaces-code/build/dockerfiles/libc-content-provider.Dockerfile

Inject che-code launcher into che-code docker image.
[The same changes](https://github.com/che-incubator/che-code/blob/main/build/dockerfiles/linux-libc.Dockerfile#L129-L139) were added to the upstream by this pull request https://github.com/che-incubator/che-code/pull/256

fix: add che-code launcher to the docker image

---

devspaces-devfileregistry/build/scripts/sync.sh
devspaces-idea/build/scripts/sync.sh
devspaces-operator/build/scripts/sync.sh
devspaces-pluginregistry/build/scripts/sync.sh
devspaces-server/build/scripts/sync.sh
devspaces-traefik/build/scripts/sync.sh

https://issues.redhat.com/browse/CRW-4801
Update sync.sh script to leave in the redhat registry info because brew now defaults to a registry that pulls in unreleased containers.

CRW-4801 Stop removing registry info from Dockerfiles

---

devspaces-udi/Dockerfile

Set [`$GOBIN` environment variable](https://pkg.go.dev/cmd/go#hdr-Environment_variables) and add it to `$PATH` 
Fixes https://issues.redhat.com/browse/CRW-4863

Set $GOBIN and add it to $PATH

---

devspaces-udi/Dockerfile

Upgrades python from 3.9 to 3.11.x (3.11.2) version
**Related issue:** https://issues.redhat.com/browse/CRW-4944
Can be tested with quay.io/vsvydenk/udi:python11
or
You can start a  python workspace with an updated image by clicking:
[![Contribute](https://www.eclipse.org/che/contribute.svg)](https://devspaces.apps.sandbox-stage.gb17.p1.openshiftapps.com/dashboard/#/https://github.com/svor/python-hello-world/tree/ds-python11) 
[screencast-bpconcjcammlapcogcnnelfmaeghhagj-2023.11.13-14_11_57.webm](https://github.com/redhat-developer/devspaces-images/assets/1271546/9136aedb-27b6-4379-904f-11d54fb60f78)

Upgrade python to 3.11

---

devspaces-udi/Dockerfile
devspaces-udi/container.yaml
devspaces-udi/content_sets.yml
devspaces-udi/etc/.stow-local-ignore
devspaces-udi/etc/entrypoint.sh

Backport of https://github.com/redhat-developer/devspaces-images/commit/93eda0eb0223b4fe036e9582f6b953701fd24df0 to 3.10 branch. Also includes https://github.com/redhat-developer/devspaces-images/commit/2f9e070a5211708c3f312cf24301b64300498464 as this wasn't backported and is required to prevent cherry-pick conflicts.

Move tools & configs from /home/user/ to /home/tooling/ (#525); upgrade python to 3.11 (#524)

---

devspaces-code/build/scripts/sync-builtins.sh

- fix initialization of script dir variables (would fail on non-3-x branch execution otherwise
- read vscode-ripgrep version straight from yarn.lock, instead of package.json (don't want to deal with possible ranges in package.json)
- edit script output

fix: fixes for Cachito built-in sync

---

devspaces-operator-bundle/Dockerfile
devspaces-operator-bundle/build/scripts/sync.sh

https://issues.redhat.com/browse/CRW-5397

chore: remove support for OCP 4.11 as its EOL soon CRW-5397

---

devspaces-pluginregistry/get-sources.sh

Get tag of che-openvsx repository during the build to pull correct version
Related issue: https://issues.redhat.com/browse/CRW-5454

fix: get correct tag of openvsx-server repo

---

devspaces-udi/Dockerfile
devspaces-udi/content_sets.repo
devspaces-udi/content_sets.yml

Integrates OpenShift Pipelines CLI (tkn) into Universal Developer Image
Related issue: https://issues.redhat.com/browse/CRW-3570
Could be tested with **registry-proxy.engineering.redhat.com/rh-osbs/devspaces-udi-rhel8:devspaces-3-rhel-8-containers-candidate-96888-20240117160501**

feat:install OS pipelines CLI

---

devspaces-operator-bundle-generated/manifests/devspaces.csv.yaml
devspaces-operator-bundle/build/scripts/sync-che-olm.sh

https://github.com/eclipse/che/issues/22485

chore: Ensure that internal registry in enabled in downstream

---

devspaces-pluginregistry/container.yaml

Related issue: https://issues.redhat.com/browse/CRW-3336
Update reference for plugin registry cachito related sources it references to https://github.com/redhat-developer/devspaces-images/commit/664a7879dfafcae34c5037b9052bd9a9faf87252 commit

Update reference for plugin registry cachito related sources

---

devspaces-operator-bundle/build/scripts/sync-che-olm.sh

https://issues.redhat.com/browse/CRW-6052

fix: Don't mention eclipse-che in operator description

---

devspaces-code/cachito/yarn.lock

Bump `ip` version
rh-pre-commit.version: 2.2.0
rh-pre-commit.check-secrets: ENABLED

chore: Bump ip version

---

devspaces-operator-bundle/build/scripts/insert-related-images-to-csv.sh

Ansible image was replaced in https://github.com/devspaces-samples/ansible-devspaces-demo/pull/28, we need to remove ghcr.io/ansible/ansible-workspace-env-reference from the list of external images
Related issue: https://issues.redhat.com/browse/CRW-6346

chore: remove ghcr.io/ansible/ansible-workspace-env-reference from EXTERNAL_IMAGES

---

devspaces-machineexec/build/dockerfiles/brew.Dockerfile
devspaces-machineexec/build/dockerfiles/rhel.Dockerfile
devspaces-machineexec/build/scripts/sync.sh
devspaces-machineexec/content_sets.yml

Update dockerfiles to use rhel-els and update sync to not overwrite them with upstream versions.
Updating content sets for rhel 9
https://issues.redhat.com/browse/CRW-3185

CRW-6054 Update Machineexec to use rhel-els 9.2

---

devspaces-configbump/build/dockerfiles/brew.Dockerfile
devspaces-configbump/build/dockerfiles/rhel.Dockerfile
devspaces-configbump/build/scripts/sync.sh
devspaces-configbump/content_sets.yml

Update dockerfiles to use rhel-els and update sync to not overwrite them with upstream versions.
Updating content sets for rhel 9
https://issues.redhat.com/browse/CRW-3185

CRW-6054 Update Configbump to use rhel-els 9.2

---

devspaces-operator/build/dockerfiles/Dockerfile
devspaces-operator/content_sets.yml

Update dockerfiles to use rhel-els and update sync to not overwrite them with upstream versions.
Updating content sets for rhel 9
https://issues.redhat.com/browse/CRW-3185

CRW-6054 Update operator to use rhel-els 9.2

---

devspaces-server/Dockerfile
devspaces-server/build/dockerfiles/brew.Dockerfile
devspaces-server/build/scripts/sync.sh
devspaces-server/content_sets.yml

Update dockerfiles to use rhel-els and update sync to not overwrite them with upstream versions.
Updating content sets for rhel 9
https://issues.redhat.com/browse/CRW-3185

CRW-6054 Update Server to use rhel-els 9.2

---

devspaces-operator/build/dockerfiles/Dockerfile

Update RPMs every build since the rhel-els images don't update as often on their own.

CRW-6054 update RPMs every build

---

devspaces-operator/build/scripts/sync-che-operator.sh

https://github.com/eclipse-che/che/issues/22932

fix: typo in syn-che-operator.sh

---

devspaces-operator-bundle/build/scripts/sync-che-olm.sh
devspaces-operator/build/scripts/sync-che-operator.sh

https://github.com/eclipse-che/che/issues/22932

fix: Updating manifests/devspaces.csv.yaml

---

devspaces-dashboard/build/scripts/sync.sh

Fix outdated links to the documentation in User Dashboard: https://access.redhat.com/documentation/en-us/red_hat_openshift_dev_spaces/
Correct link is https://docs.redhat.com/en/documentation/red_hat_openshift_dev_spaces/
Affected sources:
- 3.x: https://raw.githubusercontent.com/redhat-developer/devspaces-images/devspaces-3-rhel-8/devspaces-dashboard/packages/dashboard-frontend/assets/branding/product.json
3.15: https://raw.githubusercontent.com/redhat-developer/devspaces-images/devspaces-3.15-rhel-8/devspaces-dashboard/packages/dashboard-frontend/assets/branding/product.json
Closes https://issues.redhat.com/browse/CRW-6795

Use docs.redhat.com in links to documentation

---

devspaces-udi/Dockerfile
devspaces-udi/etc/entrypoint.sh

Add Java 21 into UDI:
Java 17 is still a default one 
Built in: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=62917751
Resulted image: registry-proxy.engineering.redhat.com/rh-osbs/devspaces-udi-rhel8:devspaces-3-rhel-8-containers-candidate-87253-20240726082019
You can test it with this [factory link](https://devspaces.apps.sandbox-stage.gb17.p1.openshiftapps.com/dashboard/#/https://gist.githubusercontent.com/svor/e7eb774091c4569af1b427d6ef6e6a88/raw/25bcd94c691e124dd2f473d4db62a0dce1934509/java21.devfile)
**Related Issue:**
https://issues.redhat.com/browse/CRW-6855

chore: install java 21 into UDI

---

devspaces-dashboard/build/scripts/sync.sh

fix: use correct path for airgap.sh

fix: use correct path for airgap.sh

---

devspaces-operator-bundle/build/scripts/sync-che-olm.sh

chore: Add samples related images into csv

chore: Add samples related images into csv

---

devspaces-operator-bundle/build/scripts/sync-che-olm.sh

chore: REmove ansible image from the RELATED_IMAGEs

chore: Remove ansible image from the RELATED_IMAGEs

---

devspaces-dashboard/build/scripts/sync.sh

There is still incorrect link in the "About" menu: `https://docs.redhat.com/**en-us**/documentation/red_hat_openshift_dev_spaces/3.16` , which is leading to 404 page error.
Correct one: `https://docs.redhat.com/*en*/documentation/red_hat_openshift_dev_spaces/3.16`

Fix link to the official documentation

---

devspaces-pluginregistry/build/scripts/sync.sh

Fix plugin registry build: https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/pluginregistry_3.x/326/console

don't update che-editors.yaml, it doesn't exist anymore

---

devspaces-dashboard/build/scripts/sync.sh

One more fix to have the link to the official documentation up to date.

Renew link to official documentation in sync.sh

---

devspaces-dashboard/build/dockerfiles/brew.Dockerfile
devspaces-dashboard/build/scripts/sync.sh
devspaces-dashboard/content_sets.yml

Updating dashboard to use rhel-els image. Installing g++ is necessary for build to run on s390x.
Fixing link to yarn since the new file has extension cjs and this wasn't caught in testing because of how cachito grabs files.

Update Dashboard to use els image and fix build issue with yarn 3 update

---

devspaces-code/build/dockerfiles/brew.Dockerfile
devspaces-traefik/Dockerfile
devspaces-traefik/build/rhel.Dockerfile

The extension on the yarn file changed from .js to .cjs so other builds dependent on that file need to be updated.

Fix name of yarn file in dashboard directory for Traefik and Code

---

devspaces-udi/Dockerfile

Related Issue: https://issues.redhat.com/browse/CRW-6270
Upgrades Maven to 3.8.5 version:
```
projects $ mvn --version
Apache Maven 3.8.5 (Red Hat 3.8.5-6)
Maven home: /usr/share/maven
Java version: 17.0.12, vendor: Red Hat, Inc., runtime: /usr/lib/jvm/java-17-openjdk-17.0.12.0.7-2.el8.x86_64
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "5.15.0-75-generic", arch: "amd64", family: "unix"
```
Built by: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=64380991
Resulted image: **registry-proxy.engineering.redhat.com/rh-osbs/devspaces-udi-rhel8:devspaces-3-rhel-8-containers-candidate-72176-20240920135412**

chore: upgrade mvn version to 3.8

---

devspaces-udi/Dockerfile

Backport changes provided by https://github.com/redhat-developer/devspaces-images/pull/636

chore: update go-toolset to latest 1.21.13 image (#636)

---

devspaces-dashboard/build/dockerfiles/brew.Dockerfile

Use rhel-els images for both stages since we're using those content repos.

Fix for CRW-7466 - 3.17 branch

---

devspaces-udi/Dockerfile
devspaces-udi/etc/.stow-local-ignore
devspaces-udi/etc/entrypoint.sh

This PR adds UBI/UDI bug fixes from upstream. They include:
* adds podman 5 support: https://github.com/devfile/developer-images/pull/209
* updates .stow-local-ignore with files in /home/user that would break running stow: https://github.com/devfile/developer-images/pull/196
* automatically detects fuse/vfs: https://github.com/devfile/developer-images/pull/198

 Add upstream UBI/UDI bug fixes
