- codeready-workspaces-plugin-intellij/content_sets.repo
- codeready-workspaces-plugin-intellij/content_sets.yml
- codeready-workspaces-plugin-java11-openj9/Dockerfile
- codeready-workspaces-plugin-java11-openj9/content_sets.repo
- codeready-workspaces-plugin-java11-openj9/content_sets.yml
- codeready-workspaces-plugin-java11/Dockerfile
- codeready-workspaces-plugin-java11/content_sets.repo
- codeready-workspaces-plugin-java11/content_sets.yml
- codeready-workspaces-plugin-java8-openj9/Dockerfile
- codeready-workspaces-plugin-java8-openj9/content_sets.repo
- codeready-workspaces-plugin-java8-openj9/content_sets.yml
- codeready-workspaces-plugin-java8/Dockerfile
- codeready-workspaces-plugin-java8/content_sets.repo
- codeready-workspaces-plugin-java8/content_sets.yml
- codeready-workspaces-plugin-kubernetes/Dockerfile
- codeready-workspaces-plugin-kubernetes/content_sets.repo
- codeready-workspaces-plugin-kubernetes/content_sets.yml
- codeready-workspaces-plugin-openshift/Dockerfile
- codeready-workspaces-plugin-openshift/content_sets.repo
- codeready-workspaces-plugin-openshift/content_sets.yml
- codeready-workspaces-stacks-cpp/Dockerfile
- codeready-workspaces-stacks-cpp/content_sets.yml
- codeready-workspaces-stacks-dotnet/Dockerfile
- codeready-workspaces-stacks-dotnet/content_sets.yml
- codeready-workspaces-stacks-golang/Dockerfile
- codeready-workspaces-stacks-golang/content_sets.yml
- codeready-workspaces-stacks-php/Dockerfile
- codeready-workspaces-stacks-php/content_sets.yml
Change-Id:...
bump to oc 4.6 and helm 3.3
Change-Id: I7102e303afc11209b631ae0eff382298a1c17acb
> bump to oc 4.6 and helm 3.3

- codeready-workspaces-plugin-kubernetes/Dockerfile
- codeready-workspaces-stacks-cpp/Dockerfile
- codeready-workspaces-stacks-dotnet/Dockerfile
- codeready-workspaces-stacks-golang/Dockerfile
- codeready-workspaces-stacks-php/Dockerfile
Signed-off-by: svor <vsvydenk@redhat.com>
- Remove node from dotnet, php, cpp, golang images;
- Update node from 10 to 12 in kubernetes-plugin image
> Cleanup images with node

- codeready-workspaces-plugin-kubernetes/Dockerfile
- codeready-workspaces-plugin-kubernetes/get-sources-jenkins.sh
Signed-off-by: Aurélien Pupier <apupier@redhat.com>
> CRW-1415 - upgrade Kamel from 1.2.0 to 1.2.1

- codeready-workspaces-plugin-java8-openj9/Dockerfile
- codeready-workspaces-plugin-java8/Dockerfile
WIP: CRW-1235 possible solution to move to python 3.8
Change-Id: I9bae3e2bf3037f13af1d96fcf8413a897d606639
> CRW-1235 move to python 3.8 w/ new lang server deps

- codeready-workspaces-plugin-java8-openj9/Dockerfile
- codeready-workspaces-plugin-java8/Dockerfile
Change-Id:...
can't use -q with microdnf
Change-Id: I9782f4798734dd70bef9f4612f9c1fab8d1f8bdc
N/A
N/A (or see commit messasge above for issue number)
N/A
> can't use -q with microdnf

- codeready-workspaces-stacks-golang/Dockerfile
Signed-off-by: svor <vsvydenk@redhat.com>
Remove npm from golang Deckerfile
> Remove npm from golang Deckerfile

- codeready-workspaces-pluginregistry/build/scripts/sync.sh
> Remove sed from plugin registry Dockerfile sync

- codeready-workspaces-pluginregistry/bootstrap.Dockerfile
> Only do yarn installation in bootstrap.Dockerfile

- codeready-workspaces-dashboard/build/scripts/sync.sh
- codeready-workspaces-dashboard/get-sources-jenkins.sh
> Cache node_modules and use them when building

- codeready-workspaces-pluginregistry/bootstrap.Dockerfile
> Remove .yarn copy line from bootstrap.Dockerfile

- codeready-workspaces-dashboard/container.yaml
Enable s390x platform for dashboard container
> Enable s390x platform for dashboard container

- codeready-workspaces-dashboard/build/dockerfiles/rhel.Dockerfile
- codeready-workspaces-dashboard/build/scripts/sync.sh
Fix bootstrap dockerfile to work with yarn1
> Fix bootstrap dockerfile to work with yarn1

- codeready-workspaces-operator/get-sources-jenkins.sh
> ci: CRW-1956 brew-friendly restic.zip implementation

- codeready-workspaces-operator/get-sources.sh
Signed-off-by: Michal Vala <mvala@redhat.com>
reflect changes needed from this che-operator upstream PR https://github.com/eclipse-che/che-operator/pull/938
> build: update crw operator with header rewrite traefik plugin

- codeready-workspaces-dashboard/Dockerfile
- codeready-workspaces-dashboard/build/dockerfiles/rhel.Dockerfile
- codeready-workspaces-dashboard/build/scripts/sync.sh
Part two of migration to Yarn 1 in eclipse/che#20138
> Dashboard fixes

- codeready-workspaces-operator/Dockerfile
> fix: syntax error

- codeready-workspaces-idea/get-sources.sh
Use proper version parameter `-version` instead `--version`.
> Use proper version parameter

- codeready-workspaces-operator-metadata/build/scripts/insert-related-images-to-csv.sh
Signed-off-by: svor <vsvydenk@redhat.com>
Update the name of RELATED_IMAGE to follow this pattern:
RELATED_IMAGES_(Image_name)_(Image_label)_(Encoded_base32_image_tag)
Where are:
-  "Image_name" - image name. Not valid chars for env variable name replaced to '_'.
-  "Image_label" - image target, for example 'devfile_registry_image'.
-  "Encoded_base32_image_tag_" - original image tag encoded to base32
for example: RELATED_IMAGE_codeready_workspaces_stacks_cpp_plugin_registry_image_GIXDCMQK
> chore: update RELATE_IMAGE name

- codeready-workspaces-operator-metadata/build/scripts/sync-che-olm-to-crw-olm.sh
```
[INFO] Removing CRD kind CheBackupServerConfiguration
[INFO] Removing CRD kind CheClusterBackup
[INFO] Removing CRD kind CheClusterRestor
```
> chore: remove backup/restore CRDs

- codeready-workspaces-operator-metadata/build/scripts/sync-che-olm-to-crw-olm.sh
- codeready-workspaces-operator-metadata/build/scripts/sync-che-operator-to-crw-operator.sh
- codeready-workspaces-operator/build/scripts/sync-che-operator-to-crw-operator.sh
The default pvcStrategy is common in upstream.
It should be the same for CRW.
> chore: don't modify pvcStrategy

- codeready-workspaces-backup/build/scripts/sync.sh
Signed-off-by: Mykola Morhun <mmorhun@redhat.com>
> Add sync script for REST backup server image

- codeready-workspaces-backup/build/scripts/sync.sh
- codeready-workspaces-backup/container.yaml
- codeready-workspaces-backup/content_sets.yml
- codeready-workspaces-backup/get-sources.sh
Signed-off-by: Mykola Morhun <mmorhun@redhat.com>
> Add get-sources script

- codeready-workspaces-operator-metadata/build/scripts/sync-che-operator-to-crw-operator.sh
https://issues.redhat.com/browse/CRW-2166
> Remove references to backup/restore controllers

- codeready-workspaces-operator-metadata/build/scripts/sync-che-olm-to-crw-olm.sh
Do not delete backup/restore CRDs from CSV.
Copy the CRDs to CRW bundle.
Signed-off-by: Mykola Morhun <mmorhun@redhat.com>
> Put back backup/restore CRDs

- codeready-workspaces-devworkspace-controller/build/scripts/sync.sh
- codeready-workspaces-operator-metadata/build/scripts/sync-che-olm-to-crw-olm.sh
- codeready-workspaces-operator-metadata/build/scripts/sync-che-operator-to-crw-operator.sh
- codeready-workspaces-operator/build/scripts/sync-che-operator-to-crw-operator.sh
CRW-2167 switch to use CRW DWO container, to be built from 0.9.x branch
N/A
N/A
> CRW-2167 switch to use CRW DWO container, to be built from 0.9.x branch

- codeready-workspaces-devfileregistry/build/scripts/sync.sh
- codeready-workspaces-operator-bundle/build/scripts/sync.sh
- codeready-workspaces-operator-metadata/build/scripts/sync.sh
- codeready-workspaces-operator/build/scripts/sync.sh
- codeready-workspaces-operator/get-sources.sh
- codeready-workspaces-pluginregistry/build.sh
- codeready-workspaces-pluginregistry/build/scripts/sync.sh
fix: updating references to VERSION.json that should be job-config.js…on and changing versionjson variable to configjson where applicable.
> Updating VERSION.json to job-config.json

- codeready-workspaces-operator-bundle/build/scripts/sync-che-olm-to-crw-olm.sh
- codeready-workspaces-operator-bundle/manifests/codeready-workspaces.csv.yaml
- codeready-workspaces-operator-metadata/build/scripts/sync-che-olm-to-crw-olm.sh
- codeready-workspaces-operator-metadata/build/scripts/sync-che-operator-to-crw-operator.sh
Signed-off-by: Flavius Lacatusu <flacatus@redhat.com>
> chore: (cherry_pick) Make ALLOW_DEVWORKSPACE_ENGINE env false in latest channel (#101)

- codeready-workspaces-dashboard/build/scripts/sync.sh
This time I built a bootstrap image locally, my chances to get further are bigger )
> fix: fix downloading yarn from github

- codeready-workspaces-operator-bundle/build/scripts/sync-che-operator-to-crw-operator.sh
> fix: Uncomment internal backup sever image

- codeready-workspaces-operator-bundle-generated/manifests/codeready-workspaces.csv.yaml
- codeready-workspaces-operator-bundle/build/scripts/sync-che-olm-to-crw-olm.sh
- codeready-workspaces-operator-bundle/build/scripts/sync-che-operator-to-crw-operator.sh
- codeready-workspaces-operator-bundle/manifests/codeready-workspaces.csv.yaml
- codeready-workspaces-operator-metadata-generated/manifests/codeready-workspaces.csv.yaml
- codeready-workspaces-operator-metadata/build/scripts/sync-che-olm-to-crw-olm.sh
- codeready-workspaces-operator-metadata/build/scripts/sync-che-operator-to-crw-operator.sh
- codeready-workspaces-operator-metadata/manifests/codeready-workspaces.csv.yaml
- codeready-workspaces-operator/build/scripts/sync-che-operator-to-crw-operator.sh
- codeready-workspaces-operator/config/manager/manager.yaml
chore: remove obsolete references to RELATED_IMAGE_single_host_gateway_native_user_mode (CRW-1956)
N/A
https://issues.redhat.com/browse/CRW-1956
N/A
> chore: remove obsolete references to RELATED_IMAGE_single_host_gateway_native_user_mode (CRW-1956)

- codeready-workspaces-operator/build/scripts/sync-che-operator-to-crw-operator.sh
> fix: Enable internal backup server image

- codeready-workspaces-operator-metadata/build/scripts/sync-che-operator-to-crw-operator.sh
- codeready-workspaces-operator/build/scripts/sync-che-operator-to-crw-operator.sh
> fix: enable gateway images

- codeready-workspaces-operator-metadata/build/scripts/sync-che-olm-to-crw-olm.sh
https://issues.redhat.com/browse/CRW-2416
fix: Include all CRs to CSV to fix CRW installation.
Signed-off-by: Oleksandr Andriienko <oandriie@redhat.com>
> fix: Include all CRs to CSV to fix CRW installation.

- codeready-workspaces-plugin-java8/build/build.sh
- codeready-workspaces-plugin-java8/build/build_lombok.sh
1.Building lombak jar inside ubi8/openjdk-11 container via ant
2. Below jars are created via latest lombok source code.
$ ls dist/
lombok-1.18.23.jar  lombok.jar  spiProcessor.jar
signed-off-by :  Amit Ghatwal <ghatwala@us.ibm.com>
> CRW-2413 : building lombok assets

- codeready-workspaces-plugin-java8/build/build_lombok.sh
Adding ability to pull jar from container
signed-off-by:  Amit Ghatwal <ghatwala@us.ibm.com>
> Fix for crw-2413

- codeready-workspaces-plugin-java8/build/build_lombok.sh
signed-off-by:  Amit Ghatwal <ghatwala@us.ibm.com>
> Adding lombok version

- codeready-workspaces-plugin-java11-openj9/Dockerfile
- codeready-workspaces-plugin-java11-openj9/get-sources.sh
- codeready-workspaces-plugin-java11/Dockerfile
- codeready-workspaces-plugin-java11/get-sources.sh
- codeready-workspaces-plugin-java8-openj9/Dockerfile
- codeready-workspaces-plugin-java8-openj9/build/build.sh
- codeready-workspaces-plugin-java8-openj9/get-sources.sh
- codeready-workspaces-plugin-java8/Dockerfile
- codeready-workspaces-plugin-java8/build/build_lombok.sh
- codeready-workspaces-plugin-java8/get-sources.sh
signed-off-by:  Amit Ghatwal <ghatwala@us.ibm.com>
> Using lombok jar assets in brew builds

- codeready-workspaces-configbump/get-sources.sh
- codeready-workspaces-plugin-java11-openj9/build/build.sh
- codeready-workspaces-plugin-java11-openj9/get-sources.sh
- codeready-workspaces-plugin-java11/build/build.sh
- codeready-workspaces-plugin-java11/get-sources.sh
- codeready-workspaces-plugin-java8-openj9/get-sources.sh
- codeready-workspaces-plugin-java8/get-sources.sh
- codeready-workspaces-plugin-kubernetes/get-sources.sh
- codeready-workspaces-stacks-golang/get-sources.sh
- codeready-workspaces-stacks-php/get-sources.sh
- codeready-workspaces-traefik/get-sources.sh
* e80bdcdd8 - (HEAD -> CRW-2504, origin/CRW-2504) don't delete noarch assets during delete phase (only delete the plugin-java8 stuff); tweak log messages nboldt@redhat.com (2 minutes ago)
* 67a781ab7 - don't delete assets when buildin j11/j11-9; tweak log messages; pass ASSET_NAME to build.sh instead of hardcoding it nboldt@redhat.com (2 minutes ago)
* 99e43b9cd - tweak download messages nboldt@redhat.com (2 minutes ago)
* 3e8d095d4 - tweak delete/publish messages nboldt@redhat.com (2 minutes ago)
N/A
N/A
Reviewers, please comment how you …
> fix: CRW-2504 don't delete assets when building j11/j11-9/j8/j8-11; tweak log messages

- codeready-workspaces-devfileregistry/bootstrap.Dockerfile
- codeready-workspaces-devfileregistry/get-sources.sh
Signed-off-by: Igor Vinokur <ivinokur@redhat.com>
Include devfiles v2 templates to tarball
> chore: Devfile Registry update tarball with devfiles v2

- codeready-workspaces-udi-openj9/Dockerfile
- codeready-workspaces-udi/Dockerfile
https://issues.redhat.com/browse/CRW-2464
> fix: &&s were breaking brew build.

- codeready-workspaces/build/scripts/sync.sh
Context https://github.com/eclipse-che/che-server/pull/262
> build: Adjust scripts to the recent changes in upstream

- devspaces-operator-bundle/build/scripts/sync.sh
small change to maybe fix builds
> CRW-2819 fix: updating util.sh to use new operator bundle name

- devspaces-udi/etc/entrypoint.sh
Port https://github.com/redhat-developer/devspaces-images/pull/218 into devspaces-3-rhel-8
> chore: add JAVA_HOME and PATH into .bashrc

- devspaces-udi/Dockerfile
Fix JAVA_HOME and PATH environment variables
> fix: correct JAVA_HOME and PATH envs

- devspaces-udi/Dockerfile
- devspaces-udi/etc/entrypoint.sh
Set default java to fix CVP tests
> fix: set default java

- devspaces-idea/build/scripts/sync.sh
- devspaces-idea/get-sources.sh
Update sync and get-sources script to get the latest changes for idea-rhel8.
fixes https://issues.redhat.com/browse/CRW-2736
> Update sync and get-sources script to get the latest changes for idea-rhel8

- devspaces-idea/build/scripts/sync.sh
> Provide fixed packages for idea-rhel8

- devspaces-idea/build/scripts/sync.sh
- devspaces-idea/get-sources.sh
> Backport idea-rhel8 updated image for DS 3.0

- devspaces-theia-endpoint/src/entrypoint.sh
> fix: sync was not done on entrypoint script

- devspaces-udi/Dockerfile
> Fix missed slash

- devspaces-udi/Dockerfile
Fix Brew error message:
```
/bin/sh: -c: line 1: syntax error: unexpected end of file
```
> Fix syntax error (unexpected end of file)

- devspaces-operator-bundle/build/scripts/sync-che-olm.sh
- devspaces-operator-bundle/build/scripts/sync-che-operator.sh
- devspaces-operator/build/scripts/sync-che-operator.sh
- devspaces-operator/config/manager/manager.yaml
https://issues.redhat.com/browse/CRW-3064
> Fix sync scripts

- devspaces-code/Dockerfile
- devspaces-code/build/dockerfiles/libc-content-provider.Dockerfile
- devspaces-code/build/scripts/collect-assets.sh
- devspaces-code/build/scripts/sync.sh
- devspaces-code/content_sets.yml
- devspaces-code/get-sources.sh
Productize che-code as an OpenShift Dev Spaces editor
See [CRW-2744](https://issues.redhat.com/browse/CRW-2744)
> feat: Productize che-code as an OpenShift Dev Spaces editor (CRW-2744)

- devspaces-operator-bundle/build/scripts/sync-che-operator.sh
- devspaces-operator/build/scripts/sync-che-operator.sh
> fix: <username>-che -> <username>-devspaces

- devspaces-code/Dockerfile
- devspaces-code/build/scripts/collect-assets.sh
Use entrypoints directly from dockerfile
> chore: Use entrypoints directly from dockerfile

- devspaces-operator-bundle/build/scripts/sync-che-olm.sh
- devspaces-operator-bundle/build/scripts/sync-che-operator.sh
- devspaces-operator/build/scripts/sync-che-operator.sh
> fix: Relace `<username>-che` with `<username>-devspaces`

- devspaces-operator-bundle/build/scripts/sync-che-olm.sh
> fix: Replace '<username>-che' with '<username>-devspaces'

- devspaces-devfileregistry/bootstrap.Dockerfile
> chore: fix build

- devspaces-devfileregistry/bootstrap.Dockerfile
don't cache projects for devfile v1
related issue: https://issues.redhat.com/browse/CRW-2985
> chore: don't cache projects for devfile v1

- devspaces-devfileregistry/Dockerfile
- devspaces-devfileregistry/build/scripts/sync.sh
remove cache projects script from dockerfile
> chore: remove cache projects script from dockerfile

- devspaces-devfileregistry/Dockerfile
- devspaces-devfileregistry/bootstrap.Dockerfile
- devspaces-devfileregistry/build/dockerfiles/Dockerfile
- devspaces-devfileregistry/build/scripts/sync.sh
revert cache projects procedure
> chore: revert cache projects procedure

- devspaces-code/build/dockerfiles/libc-content-provider.Dockerfile
Add debug output to list all available gulp tasks.
> Add debug output

- devspaces-devfileregistry/Dockerfile
> chore: update Dockerfile to add resources folder

- devspaces-code/build/dockerfiles/libc-content-provider.Dockerfile
Fix build of dockerimage for Code
> fix: Fix build of dockerimage for Code

- devspaces-udi/Dockerfile
- devspaces-udi/etc/entrypoint.sh
Install Java 17 into UDI
Related issue: https://issues.redhat.com/browse/CRW-3075 and https://issues.redhat.com/browse/CRW-3074
> chore: install java 17 into UDI

- devspaces-configbump/get-sources.sh
> Fix for CRW-3135

- devspaces-code/cvp-owners.yml
- devspaces-code/cvp.yml
- devspaces-code/tests/basic-test.yaml
Change-Id:...
add CVP tests and owners
Change-Id: Ia9d30d2ea9ace68e499ecf178a62e33c6bed5f12
Signed-off-by: Nick Boldt <nickboldt@gmail.com>
N/A
N/A
> add CVP tests and owners

- devspaces-configbump/Dockerfile
In the original commit I updated brew.Dockerfile but not the Dockerfile itself because I figured it would just be updated automatically with the next build, but it looks like there hasn't been one so I'll just update it manually now.
> Updating dockerfile

- devspaces-traefik/build/rhel.binary.Dockerfile
- devspaces-traefik/build/rhel.container.Dockerfile
- devspaces-traefik/build/scripts/sync.sh
move up to node 14 and install yarn; also fix path to static files
Change-Id: Ib18850f3774da39130fbb136345442f4c92be589
N/A
N/A
> move up to node 14 and install yarn; also fix path to static files

- devspaces-operator-bundle/build/scripts/sync-che-olm.sh
- devspaces-operator-bundle/build/scripts/sync-che-operator.sh
- devspaces-operator/build/scripts/sync-che-operator.sh
https://issues.redhat.com/browse/CRW-3263
> chore: Include newer ose proxy images in operator deployment

- devspaces-udi/Dockerfile
- devspaces-udi/container.yaml
Signed-off-by: Mykhailo Kuznietsov <mkuznets@redhat.com>
> [WIP] feat: Add golangci-lint w/Cachito build to UDI

- devspaces-operator/Dockerfile
- devspaces-operator/build/dockerfiles/Dockerfile
For https://issues.redhat.com/browse/CRW-3138.
Should fix brew build.
> fix: change location names to match container.yaml/job-config.json

- devspaces-operator/Dockerfile
- devspaces-operator/Makefile
- devspaces-operator/bootstrap.Dockerfile
- devspaces-operator/build/scripts/sync.sh
- devspaces-operator/build/scripts/util.sh
- devspaces-operator/get-sources.sh
to DEV_WORKSPACE_CONTROLLER
For https://issues.redhat.com/browse/CRW-3138
> chore: update DEV_WORKSPACE_CONTROLLER_VERSION 

- devspaces-operator/Dockerfile
- devspaces-operator/build/dockerfiles/Dockerfile
> Fix: needed && \ between lines

- devspaces-udi/Dockerfile
Added .NET7 to the devspaces-udi Dockerfile 
.NET7 includes support for new architecture Power (ppc64le).
https://issues.redhat.com/browse/CRW-3512
> switch to .NET7 (add support for ppc64le)

- devspaces-udi/Dockerfile
https://issues.redhat.com/browse/CRW-3585
> Add Git LFS support to UDI

- devspaces-server/build/scripts/sync.sh
CRW-3099 generate fetch-artifacts-pnc.yaml from bacon pnc (WIP, requires bacon install and config)
Change-Id: I4f6c2568c1277f444416dca3ba89f7567973f669
N/A
https://issues.redhat.com/browse/CRW-3099
depends on https://gitlab.cee.redhat.com/codeready-workspaces/ansible-scripts/-/merge_requests/49 being merged successfully and applied to worker nodes
N/A
> CRW-3099 generate fetch-artifacts-pnc.yaml from bacon pnc (WIP, requires bacon install and config)

- devspaces-operator-bundle/build/scripts/sync-che-olm.sh
https://issues.redhat.com/browse/CRW-3785
> fix: alm-example, headerMessage.show must be bool

- devspaces-dashboard/build/scripts/sync.sh
- devspaces-operator-bundle/build/README_icon.md
- devspaces-operator-bundle/build/scripts/digestExcludeList
- devspaces-operator-bundle/build/scripts/sync-che-olm.sh
- devspaces-operator-bundle/container.yaml
chore: feat: remove theia from dashboard; change dashboard notice to removal (not deprecation) (CRW-3489, CRW-3663) #408
Change-Id: I98316ebe60801f31172e852655eccfba49fe55da
N/A
https://issues.redhat.com/browse/CRW-3489 
https://issues.redhat.com/browse/CRW-3663 
See also 
https://issues.redhat.com/browse/CRW-4077
N/A
> chore: feat: remove theia from dashboard; change dashboard notice to removal (not deprecation) (CRW-3489, CRW-3663)

- devspaces-operator-bundle/build/scripts/sync-che-olm.sh
chore: fix: CRW-4112 link to deprecated doc section rather than the specific subsection
Change-Id: I0faed1c8881aa5864aa751cf8ebfabc33c7b9292
N/A
https://issues.redhat.com/browse/CRW-4112
N/A
> chore: fix: CRW-4112 link to deprecated doc section rather than the specific subsection

- devspaces-operator-bundle/build/scripts/sync-che-olm.sh
chore: fix: https://issues.redhat.com/browse/CRW-4125 exclude freshmaker respins from the CRD
Change-Id: I30f4b0fe014e8c8eda99096461ce174983cb062c
N/A
N/A
> chore: fix: https://issues.redhat.com/browse/CRW-4125 exclude freshmaker respins from the CRD

- devspaces-operator-bundle/build/scripts/sync-che-olm.sh
- devspaces-operator-bundle/build/scripts/sync-che-operator.sh
- devspaces-operator/build/scripts/sync-che-operator.sh
https://github.com/eclipse/che/issues/22064
> feat: Configure defaults from env var

- devspaces-operator-bundle/build/scripts/sync-che-olm.sh
- devspaces-operator-bundle/build/scripts/sync-che-operator.sh
- devspaces-operator/build/scripts/sync-che-operator.sh
https://issues.redhat.com/browse/CRW-4077
> fix: detecting UDI_IMAGE

- devspaces-udi/Dockerfile
> Arbitrary users in UDI should have $HOME write access (#460)

- devspaces-devfileregistry/Dockerfile
- devspaces-devfileregistry/bootstrap.Dockerfile
- devspaces-devfileregistry/build/dockerfiles/Dockerfile
- devspaces-pluginregistry/bootstrap.Dockerfile
Set python-38 image to python-38:1-127.1684490929 since latest has signing issues
> CRW-4359 Set python-38 image to python-38:1-127.1684490929

- devspaces-operator-bundle/build/scripts/insert-related-images-to-csv.sh
add quay.io/devspaces/ansible-creator-ee image with digest into related images list
> feat: add quay.io/devspaces/ansible-creator-ee into related images list

- devspaces-operator-bundle/build/scripts/insert-related-images-to-csv.sh
Backport [changes](https://github.com/redhat-developer/devspaces-images/pull/467) from devspaces-3-rhel-8 related to the excluding ansible image
> chore: don't add ansible-creator-ee image as a related image env variable

- devspaces-operator-bundle/build/scripts/sync-che-olm.sh
- devspaces-operator-bundle/build/scripts/sync-che-operator.sh
- devspaces-operator/build/scripts/sync-che-operator.sh
chore: bump to openshift4/ose-kube-rbac-proxy and ose-oauth-proxy from :v4.13 tag
Change-Id: I97570e80715d99960672f6f07427e99b51d9eff1
N/A
N/A
> chore: bump to openshift4/ose-kube-rbac-proxy and ose-oauth-proxy from :v4.13 tag

- devspaces-udi/Dockerfile
Updates to UDI Dockerfile to make build work
> Fixes to kubedock build

- devspaces-devfileregistry/build/scripts/sync.sh
CRW-4801, CRW-4843 don't switch from ubi8 to rhel8 as we now include the full registry reference; DO trim version so we get the latest
N/A
N/A
> CRW-4801, CRW-4843 don't switch from ubi8 to rhel8 as we now include the full registry reference; DO trim version so we get the latest

- devspaces-operator-bundle/build/scripts/sync-che-olm.sh
https://issues.redhat.com/browse/CRW-4848
> fix: Update devspace operator deployment labels

- devspaces-traefik/build/scripts/checkgoMod.sh
- devspaces-traefik/build/scripts/sync.sh
chore: add new devspaces-traefik/build/scripts/checkgoMod.sh script to validate go.mod versions (CRW-4868)
N/A
N/A
> chore: add new devspaces-traefik/build/scripts/checkgoMod.sh script to validate go.mod versions (CRW-4868)

- devspaces-udi/Dockerfile
Cherry pick of https://github.com/redhat-developer/devspaces-images/pull/505
Fixes https://issues.redhat.com/browse/CRW-4863
> Set $GOBIN and add it to $PATH

- devspaces-operator-bundle/Dockerfile
- devspaces-operator-bundle/build/scripts/sync.sh
chore: CRW-4923 drop support for OCP 4.10 as it's now EOL
N/A
N/A
> chore: CRW-4923 drop support for OCP 4.10 as it's now EOL

- devspaces-traefik/Dockerfile
- devspaces-udi/Dockerfile
- devspaces-udi/build/php_xdebug.Dockerfile
chore: Update from rhel8/go-toolset:1.19.10-16 to rhel8/go-toolset:1.19.13-2
chore: Update from ubi8-minimal:8.7-1049.1675784874 to ubi8-minimal:8.8-1072
chore: Update from ubi8-minimal:8.8-1037 to ubi8-minimal:8.8-1072
N/A
https://issues.redhat.com/browse/CRW-4925?focusedId=23285789&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-23285789
https://access.redhat.com/errata/RHSA-2023:5721
N/A
> chore: Update to rhel8/go-toolset:1.19.13-2 and ubi8-minimal:8.8-1072

- devspaces-code/get-sources.sh
- devspaces-configbump/get-sources.sh
- devspaces-devfileregistry/get-sources.sh
- devspaces-idea/get-sources.sh
- devspaces-imagepuller/get-sources.sh
- devspaces-machineexec/get-sources.sh
- devspaces-operator/get-sources.sh
- devspaces-traefik/get-sources.sh
- devspaces-udi/get-sources.sh
chore: CRW-4821 partial backport of switch to use brew instead of rhpkg for container-build commands
N/A
N/A
> chore: CRW-4821 partial backport of switch to use brew instead of rhpkg for container-build commands

- devspaces-code/cvp.yml
- devspaces-configbump/build/dockerfiles/brew.Dockerfile
- devspaces-dashboard/build/dockerfiles/brew.Dockerfile
- devspaces-devfileregistry/Dockerfile
- devspaces-devfileregistry/cvp.yml
- devspaces-idea/cvp.yml
- devspaces-imagepuller/build/dockerfiles/brew.Dockerfile
- devspaces-machineexec/build/dockerfiles/brew.Dockerfile
- devspaces-operator-bundle/cvp-owners.yml
- devspaces-operator/Dockerfile
- devspaces-pluginregistry/Dockerfile
- devspaces-pluginregistry/cvp.yml
- devspaces-server/Dockerfile
- devspaces-server/cvp.yml
- devspaces-traefik/Dockerfile
to remove people who should no longer be receiving emails.
> Update cvp and dockerfile owners 

- devspaces-code/cvp.yml
- devspaces-configbump/build/dockerfiles/brew.Dockerfile
- devspaces-dashboard/build/dockerfiles/brew.Dockerfile
- devspaces-devfileregistry/Dockerfile
- devspaces-devfileregistry/cvp.yml
- devspaces-idea/cvp.yml
- devspaces-imagepuller/build/dockerfiles/brew.Dockerfile
- devspaces-machineexec/build/dockerfiles/brew.Dockerfile
- devspaces-operator-bundle/cvp-owners.yml
- devspaces-operator/Dockerfile
- devspaces-pluginregistry/Dockerfile
- devspaces-pluginregistry/cvp.yml
- devspaces-server/Dockerfile
- devspaces-server/cvp.yml
- devspaces-traefik/Dockerfile
- devspaces-udi/cvp.yml
> Cherry-pick changes to 3.10

- devspaces-operator-bundle/cvp-owners.yml
Send `devspaces-operator-bundle` image CVP build email notifications to ibuziuk@redhat.com
> Send devspaces-operator-bundle CVP build notifications to ibuziuk@redhat.com

- devspaces-operator-bundle/Dockerfile
- devspaces-operator-bundle/build/scripts/sync.sh
https://issues.redhat.com/browse/CRW-5397
> chore: remove support for OCP 4.11 as its EOL soon 

- devspaces-dashboard/packages/dashboard-frontend/assets/branding/product.json
https://issues.redhat.com/browse/CRW-5383
> fix: Update documentation links

- devspaces-code/build/dockerfiles/brew.Dockerfile
This PR aims to fix the default git clone issue not being set to /projects in DevSpaces Code: https://issues.redhat.com/browse/CRW-5665. It is essentially a continuation of the downstream port of https://github.com/che-incubator/che-code/pull/314. The [upstream commit ](https://github.com/che-incubator/che-code/commit/64b89c5a2954be173fc4ea63e6646a1e38064bf0) wasn't fully backported by the [auto-sync](https://github.com/redhat-developer/devspaces-images/commit/69aed2eb920b4f7cd4a34139121a12f71a63c320) due to DevSpaces Code having it's own dockerfile.
It is possible that my changes could be simplified, however I will be on PTO starting tomorrow February 14th till February 21st and will not have the chance to simplify my changes, update this PR or run new brew builds. Thus, the reviewer(s) …
> Fix: CRW-5665 copy remote settings.json into container during build

- devspaces-devfileregistry/build/scripts/check_referenced_images.sh
Since ansible image was updated in the sample (PR with changes: https://github.com/devspaces-samples/ansible-devspaces-demo/pull/28) we need to update it in the script that validate images
Related issue: https://issues.redhat.com/browse/CRW-6290
> chre: update ansible image in allowed list 

- devspaces-operator-bundle/build/scripts/sync-che-olm.sh
https://issues.redhat.com/browse/CRW-6352
> fix: Replace Che links with DevSpaces ones

- devspaces-operator-bundle/build/scripts/sync-che-operator.sh
- devspaces-operator-bundle/build/scripts/sync.sh
- devspaces-operator/build/scripts/sync-che-operator.sh
https://github.com/eclipse-che/che/issues/22932
> fix: sync.sh

- devspaces-code/build/dockerfiles/brew.Dockerfile
see https://github.com/redhat-developer/devspaces-images/pull/577
> fix: fix build of devspaces-code

- devspaces-configbump/build/dockerfiles/brew.Dockerfile
- devspaces-configbump/build/dockerfiles/rhel.Dockerfile
- devspaces-idea/Dockerfile
- devspaces-imagepuller/build/dockerfiles/Dockerfile
- devspaces-imagepuller/build/dockerfiles/brew.Dockerfile
- devspaces-machineexec/build/dockerfiles/brew.Dockerfile
- devspaces-machineexec/build/dockerfiles/rhel.Dockerfile
- devspaces-operator/Dockerfile
- devspaces-operator/build/dockerfiles/Dockerfile
- devspaces-server/build/dockerfiles/brew.Dockerfile
UpdateBaseImages script looks at the comment to check for new images.
> CRW-6054 Fix dockerfile comments so updateBaseImages script works

- devspaces-traefik/Dockerfile
- devspaces-traefik/build/rhel.Dockerfile
Also revert back to normal containers to match main branch
> Install go 1.20.12 specifically

- devspaces-operator/build/dockerfiles/Dockerfile
https://issues.redhat.com/browse/CRW-6597
> fix: copy editor defintion in operator image

- devspaces-udi/Dockerfile
Upgrade .NET to 8.0 version
Built in https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=62892593
**Resulted image:** quay.io/vsvydenk/udi:dotnet80
**Related issue:** https://issues.redhat.com/browse/CRW-6827
**How to test:**
execute `dotnet --version` in the container
> [UDI] Install .NET 8.0

- devspaces-dashboard/build/scripts/sync.sh
fix: Exclude samples/index.json
> fix: Exclude samples/index.json

- devspaces-operator-bundle/build/scripts/sync-che-olm.sh
chore: Replace related images on dashboard startup
> chore: Replace related images on dashboard startup

- devspaces-operator-bundle/cvp-owners.yml
Let @artaleks9 be receiving emails with devspaces-operator-bundle CVP build details.
> Add oshmarai@redhat.com to devspaces-operator-bundle/cvp-owners.yml

- devspaces-operator-bundle/build/scripts/sync-che-olm.sh
- devspaces-operator/build/scripts/sync-che-operator.sh
https://issues.redhat.com/browse/CRW-7160
> fix: Fix incorrect setting RELATED_IMAGE for che-idea editor definition

- devspaces-operator-bundle/cvp-owners.yml
This is cherry-pick of commit https://github.com/redhat-developer/devspaces-images/pull/612
> Add oshmarai@redhat.com to devspaces-operator-bundle/cvp-owners.yml 

- devspaces-udi/Dockerfile
Upgrades NodeJS to v20:
- node:  v20.16.0
- npm:   10.8.1
Built in https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=63858962
**Related issue:** https://issues.redhat.com/browse/CRW-6904
> chore: upgrade node to version 20

- devspaces-operator-bundle/build/scripts/sync-che-olm.sh
- devspaces-operator-bundle/build/scripts/sync-che-operator.sh
- devspaces-operator/build/scripts/sync-che-operator.sh
https://issues.redhat.com/browse/CRW-7199
> CRW-7199: Use v4.15 ose-kube-rbac-proxy

- devspaces-operator-bundle/build/scripts/sync-che-olm.sh
- devspaces-operator-bundle/build/scripts/sync-che-operator.sh
- devspaces-operator/build/scripts/sync-che-operator.sh
https://issues.redhat.com/browse/CRW-7199
> CRW-1799 Update ose-oauth-proxy

- devspaces-operator-bundle/build/scripts/sync-che-olm.sh
- devspaces-operator-bundle/build/scripts/sync-che-operator.sh
- devspaces-operator/build/scripts/sync-che-operator.sh
ose-oauth-proxy only goes to v4.14 so switch proxies to that for consistency.
> CRW-7199 Update to use v4.14.

- devspaces-operator-bundle/build/scripts/sync-che-olm.sh
- devspaces-operator-bundle/build/scripts/sync-che-operator.sh
- devspaces-operator/build/scripts/sync-che-operator.sh
Making changes to main since the issue affecting 4.12 will remain until next Februaryish
> CRW-7199 Updating proxy images to use v4.14

- devspaces-code/container.yaml
Update container.yaml to remove devspaces-code/cachito since it was removed.
> Fix Code build

- devspaces-code/container.yaml
Update container.yaml to remove devspaces-code/cachito since it was removed.
> Fix Code build in 3.17

- devspaces-code/build/scripts/sync.sh
- devspaces-code/container.yaml
https://issues.redhat.com/browse/CRW-7465
> Remove the line from the sync.sh that seems to be adding the cachito folder back to the container.yaml

- devspaces-imagepuller/build/scripts/sync.sh
https://issues.redhat.com/browse/CRW-8334
> Fix sync so it doesn't break the vendor folder
